# development: 
#   stripe_secret_key: <%= ENV["STRIPE_SECRET_TEST_KEY"]%>
#   stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_TEST_KEY"]%>

# production: 
#   stripe_secret_key: <%= ENV["STRIPE_SECRET_TEST_KEY"]%>
#   stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_TEST_KEY"]%>


  # pk_test_51HN5XFKYkELgOBXmFpEJqnw7WynOS5irzHdnuse7CMysCArWYZPwclIdO73m8Ot8CVNn6pQANPfuPkbDmLk3HRdD00ss20lGUO