development: 
  stripe_secret_key: sk_test_51HN5XFKYkELgOBXmxEZEVpQtJTFCHhhmCtDGvagjbivSA9q9njOt3fJ408I2xTbxu7uYll4uW4DigGeX3rkN59eb001S4vtlNz
  stripe_publishable_key: pk_test_51HN5XFKYkELgOBXmFpEJqnw7WynOS5irzHdnuse7CMysCArWYZPwclIdO73m8Ot8CVNn6pQANPfuPkbDmLk3HRdD00ss20lGUO

production: 
  stripe_secret_key: sk_test_51HN5XFKYkELgOBXmxEZEVpQtJTFCHhhmCtDGvagjbivSA9q9njOt3fJ408I2xTbxu7uYll4uW4DigGeX3rkN59eb001S4vtlNz
  stripe_publishable_key: pk_test_51HN5XFKYkELgOBXmFpEJqnw7WynOS5irzHdnuse7CMysCArWYZPwclIdO73m8Ot8CVNn6pQANPfuPkbDmLk3HRdD00ss20lGUO
